-- CreateTable
CREATE TABLE "Scenario" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL DEFAULT 'Default',
    "constructionCost" INTEGER NOT NULL DEFAULT 10000000,
    "equipmentCost" INTEGER NOT NULL DEFAULT 4000000,
    "jobsPerMonth" INTEGER NOT NULL DEFAULT 200,
    "pricePerJob" INTEGER NOT NULL DEFAULT 25000,
    "cogsPercent" INTEGER NOT NULL DEFAULT 70,
    "staffCost" INTEGER NOT NULL DEFAULT 430000,
    "rent" INTEGER NOT NULL DEFAULT 70000,
    "paintCost" INTEGER NOT NULL DEFAULT 300000,
    "utilities" INTEGER NOT NULL DEFAULT 120000,
    "misc" INTEGER NOT NULL DEFAULT 100000,
    "software" INTEGER NOT NULL DEFAULT 30000,
    "capacityPercent" INTEGER NOT NULL DEFAULT 100,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Scenario_pkey" PRIMARY KEY ("id")
);
